server:
  name: gin-study
  read_timeout: 60s
  write_timeout: 60s
  address: :8000
  run_mode: debug # 生产上使用 release

logger:
  level: info
  file: logs/user.log

mariadb:
  address: 127.0.0.1:3306
  username: study
  password: password
  database: study
  max_idle_connections: 100
  max_open_connections: 100
  max_connection_life_time: 10s

redis:
  address: 127.0.0.1:6379
  password: 123456
  db: 0