// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/send/code": {
            "post": {
                "description": "根据不同的请求类型发送短信验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "短信验证码",
                "parameters": [
                    {
                        "description": "发送验证码请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SendCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.SendCodeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "user.SendCodeRequest": {
            "type": "object",
            "required": [
                "mobile",
                "type"
            ],
            "properties": {
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "type": {
                    "description": "@param type body string true \"发送验证码类型\" Enums(login, register) default(login)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.SendCodeType"
                        }
                    ]
                }
            }
        },
        "user.SendCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        },
        "user.SendCodeType": {
            "type": "string",
            "enum": [
                "login"
            ],
            "x-enum-varnames": [
                "SendCodeTypeLogin"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "使用token传递用户认证信息",
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "gin学习项目",
	Description:      "使用gin框架学习web开发时会使用到的功能.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
